GET http://localhost:5135/games

###

GET http://localhost:5135/games/2

###

POST http://localhost:5135/games
Content-Type: application/json

{
  "title": "NFS Heat",
  "description": "Racing",
  "GenreId": 3,
  "price": 49.99,
  "DateRelease": "2024-05-01"
}

###
PUT http://localhost:5135/games/2
Content-Type: application/json

{
  "title": "NFS Underground 2",
  "description": "Racing",
  "GenreId": 3,
  "price": 49.99,
  "DateRelease": "2024-05-01"
}

###
DELETE http://localhost:5135/games/1
